#!/bin/bash

d=`date +%Y%m%d-%H%M%S`

#PBS -S /bin/bash
#PBS -l mem=6g
#PBS -r n
#PBS -N train-$JOBID
#PBS -M jonathan.esterhazy@gmail.com
#PBS -m bea
#PBS -o train.out.$d
#PBS -e train.err.$d

cd $PBS_O_WORKDIR
echo "Current working directory is `pwd`"

echo "Starting run at: `date`"
/home/jester/hdpa/target/hdpa-0.0.2-dist/run.sh com.bronzespear.hdpa.TrainHdpa /home/jester/data/nyt-random-d100-t5000 1000 5
echo "Program finished with exit code $? at: `date`"

